package com.usy.personblog.models;

public class BlogTags {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_tags.blogs_id
     *
     * @mbg.generated Thu Oct 22 12:19:07 CST 2020
     */
    private Long blogsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_tags.tags_id
     *
     * @mbg.generated Thu Oct 22 12:19:07 CST 2020
     */
    private Long tagsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_tags.blogs_id
     *
     * @return the value of t_blog_tags.blogs_id
     *
     * @mbg.generated Thu Oct 22 12:19:07 CST 2020
     */
    public Long getBlogsId() {
        return blogsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_tags.blogs_id
     *
     * @param blogsId the value for t_blog_tags.blogs_id
     *
     * @mbg.generated Thu Oct 22 12:19:07 CST 2020
     */
    public void setBlogsId(Long blogsId) {
        this.blogsId = blogsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_tags.tags_id
     *
     * @return the value of t_blog_tags.tags_id
     *
     * @mbg.generated Thu Oct 22 12:19:07 CST 2020
     */
    public Long getTagsId() {
        return tagsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_tags.tags_id
     *
     * @param tagsId the value for t_blog_tags.tags_id
     *
     * @mbg.generated Thu Oct 22 12:19:07 CST 2020
     */
    public void setTagsId(Long tagsId) {
        this.tagsId = tagsId;
    }
}