package com.usy.personblog.mapper;

import com.usy.personblog.models.BlogTags;
import com.usy.personblog.models.BlogTagsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BlogTagsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_tags
     *
     * @mbg.generated Thu Oct 22 12:19:07 CST 2020
     */
    long countByExample(BlogTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_tags
     *
     * @mbg.generated Thu Oct 22 12:19:07 CST 2020
     */
    int deleteByExample(BlogTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_tags
     *
     * @mbg.generated Thu Oct 22 12:19:07 CST 2020
     */
    int insert(BlogTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_tags
     *
     * @mbg.generated Thu Oct 22 12:19:07 CST 2020
     */
    int insertSelective(BlogTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_tags
     *
     * @mbg.generated Thu Oct 22 12:19:07 CST 2020
     */
    List<BlogTags> selectByExampleWithRowbounds(BlogTagsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_tags
     *
     * @mbg.generated Thu Oct 22 12:19:07 CST 2020
     */
    List<BlogTags> selectByExample(BlogTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_tags
     *
     * @mbg.generated Thu Oct 22 12:19:07 CST 2020
     */
    int updateByExampleSelective(@Param("record") BlogTags record, @Param("example") BlogTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_tags
     *
     * @mbg.generated Thu Oct 22 12:19:07 CST 2020
     */
    int updateByExample(@Param("record") BlogTags record, @Param("example") BlogTagsExample example);
}